//login actions
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGOUT = "LOGOUT";
export const LOAD_PROFILE = "LOAD_PROFILE";

//video actions
export const HOME_VIDEOS_SUCCESS = "HOME_VIDEOS_SUCCESS";
export const HOME_VIDEOS_FAILURE = "HOME_VIDEOS_FAILURE";
export const HOME_VIDEOS_REQUEST = "HOME_VIDEOS_REQUEST";
export const SET_VIDEO_DETAILS = "SET_VIDEO_DETAILS";
// // export const SET_CHANNEL_ICON = "SET_CHANNEL_ICON";

export const SELECTED_VIDEO_REQUEST = "SELECTED_VIDEO_REQUEST";
export const SELECTED_VIDEO_SUCCESS = "SELECTED_VIDEO_SUCCESS";
export const SELECTED_VIDEO_FAILURE = "SELECTED_VIDEO_FAILURE";

//channel actions
export const CHANNEL_DETAILS_REQUEST = "CHANNEL_DETAILS_REQUEST";
export const CHANNEL_DETAILS_SUCCESS = "CHANNEL_DETAILS_SUCCESS";
export const CHANNEL_DETAILS_FAILURE = "CHANNEL_DETAILS_FAILURE";

//subscription
export const SET_SUBSCRIPTION_STATUS = "SET_SUBSCRIPTION_STATUS";

//comments
export const COMMENTS_LIST_REQUEST = "COMMENTS_LIST_REQUEST";
export const COMMENTS_LIST_SUCCESS = "COMMENTS_LIST_SUCCESS";
export const COMMENTS_LIST_FAILURE = "COMMENTS_LIST_FAILURE";

//add comment
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_FAILURE = "CREATE_COMMENT_FAILURE";

//related videos
export const RELATED_VIDEOS_REQUEST = "RELATED_VIDEOS_REQUEST";
export const RELATED_VIDEOS_SUCCESS = "RELATED_VIDEOS_SUCCESS";
export const RELATED_VIDEOS_FAILURE = "RELATED_VIDEOS_FAILURE";

//Search videos
export const SEARCH_VIDEO_REQUEST = "SEARCH_VIDEO_REQUEST";
export const SEARCH_VIDEO_SUCCESS = "SEARCH_VIDEO_SUCCESS";
export const SEARCH_VIDEO_FAILURE = "SEARCH_VIDEO_FAILURE";

//Subscriptions channel action
export const SUBSCRIPTIONS_CHANNEL_REQUEST = "SUBSCRIPTIONS_CHANNEL_REQUEST";
export const SUBSCRIPTIONS_CHANNEL_SUCCESS = "SUBSCRIPTIONS_CHANNEL_SUCCESS";
export const SUBSCRIPTIONS_CHANNEL_FAILURE = "SUBSCRIPTIONS_CHANNEL_FAILURE";

//channel videos actions
export const CHANNEL_VIDEOS_REQUEST = "CHANNEL_VIDEOS_REQUEST";
export const CHANNEL_VIDEOS_SUCCESS = "CHANNEL_VIDEOS_SUCCESS";
export const CHANNEL_VIDEOS_FAILURE = "CHANNEL_VIDEOS_FAILURE";

//liked videos action
export const LIKED_VIDEOS_REQUEST = "LIKED_VIDEOS_REQUEST";
export const LIKED_VIDEOS_SUCCESS = "LIKED_VIDEOS_SUCCESS";
export const LIKED_VIDEOS_FAILURE = "LIKED_VIDEOS_FAILURE";

//subscribe Channel
export const SUBSCRIBE_CHANNEL_REQUEST = "SUBSCRIBE_CHANNEL_REQUEST";
export const SUBSCRIBE_CHANNEL_SUCCESS = "SUBSCRIBE_CHANNEL_SUCCESS";
export const SUBSCRIBE_CHANNEL_FAILURE = "SUBSCRIBE_CHANNEL_FAILURE";

//subscribe Channel
export const LIKE_VIDEO_REQUEST = "LIKE_VIDEO_REQUEST";
export const LIKED_VIDEO_SUCCESS = "LIKED_VIDEO_SUCCESS";
export const LIKED_VIDEO_FAILURE = "LIKED_VIDEO_FAILURE";
